parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: 'module'
  project: 'tsconfig.json'
plugins:
  - '@typescript-eslint/eslint-plugin'
extends:
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
env:
  node: true
root: true
rules:
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'error'
  '@typescript-eslint/no-unused-vars': 'error'
  '@typescript-eslint/ban-types': 'off'
  curly:
    - error
    - all
  no-unused-vars: 'off'
