apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: knexion-core
  description: The core lib of knexion
  annotations:
    backstage.io/techdocs-ref: dir:../..
  tags:
    - postgres
    - database
    - nestjs
  links:
    - url: https://github.com/seedium/knexion/tree/main/packages/core
      title: Repository
      icon: github
spec:
  type: library
  lifecycle: experimental
  owner: user:default/k.zgara
  subcomponentOf: knexion
