name: Pull Request

on: [pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Format
        run: yarn prettier '**/*.ts' --check

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Lint source code
        run: yarn eslint 'packages/**/lib/**/*.ts'
      - name: Lint test code
        run: yarn eslint -c .eslintrc.spec.yaml --fix 'packages/**/tests/**/*.spec.ts'

  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Lint commit
        uses: wagoid/commitlint-github-action@v5.3.1
        with:
          configFile: ./.commitlintrc.json
          failOnWarnings: true

  build:
    needs:
      - format
      - lint
      - lint-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn build

  tests:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: example
          POSTGRES_DB: test_integration
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install --immutable
      - name: Run tests
        run: yarn test
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: example
          POSTGRES_DB: test_integration
          POSTGRES_PORT: 5432
